### PR TITLE
dt/scf: introduce a dt helper to check if device is shared

### PR DESCRIPTION
**Pull request by aanisov**
This patch series addresses issue #35

### CODE REVIEW

**Comment by aanisov** [comment]
comments please

**Comment by aanisov** [comment]
It is not decided yet what to do with a device tree node if it has a "xen,coproc"  property but there is no correspondent coproc driver within SCF. Should we insert this node for device tree dom0 or should we hide it from dom0. After agreeing on this question patch "dt/scf: introduce a dt helper to check if device is shared" should be reconsidered.

**Comment by andr2000** [comment]
at least during debug, when one wants to compare "bare-metal" behavior to Xen platform driver in place, it is very easy with the patch reverted.
I would leave it as is and open an issue so it is known and accounted

**Comment by aanisov** [comment]
Actually the point here is a bit different, I'm going to refactor the code inside the `if` along with scf configuration redesign. The intention is to introduce the simple helper.

**Comment by aanisov** [comment]
OK I would close the PR, will keep the helper introduction inside the redesign series.

**Pull request closed without merging**
