### PR TITLE
Rpi5 dev: port patches from meta

### PR DESCRIPTION
**Pull request by GrygiriiS**
It's possible to port RPI5 Xen  patches from meta-xt-rpi5 now hence there is a "rpi5_dev" branch.

Patches are ported without any changes from https://github.com/xen-troops/meta-xt-rpi5/tree/main/recipes-extended/xen/files, so they are already reviewed and tested.

The switch to standalone Xen rpi5_dev branch is required because of SCMI feature development which will introduce much more patches and holding them in **meta** will become unmaintainable.

More over, SCMI is based on these patches.

Pls, advice regarding tags if required.

### CODE REVIEW

**Comment by GrygiriiS** [comment]
@lorc @oleksiimoisieiev @otyshchenko1

**Comment by oleksiimoisieiev** [comment]
LGTM `Reviewed-by: Oleksii Moisieiev <oleksii_moisieiev@epam.com>`

**Review by lorc — APPROVED** [review]
`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by GrygiriiS** [comment]
Could it be merged?

**Pull request merged**
