### PR TITLE
Rebase dangling XT patches onto RELEASE-4.10.0 (updated)

### PR DESCRIPTION
**Pull request by otyshchenko1**
This is the copy of the original PR @aanisov did, but contains more updated "non-shared iommu" + "ipmmu-vmsa" patches.
https://github.com/xen-troops/xen/pull/107

Also it contains updated patch I was concerned about:
https://github.com/xen-troops/xen/pull/107/commits/2487ba30e77286b30ca2a26dfd05daf2156e6577

### CODE REVIEW

**Comment by otyshchenko1** [comment]
For anybody who will want to see the difference between them:
`git fetch xen-troops pull/107/head:4.10-rebase1`
`git fetch xen-troops pull/108/head:4.10-rebase2`
`git diff 4.10-rebase1..4.10-rebase2`

**Comment by al1img** [comment]
libxl: add libxl__is_driver_domain function - ok
libxl: add vgsx device - ok
libxl: add backend type to vkb  - ok
docs: add PV sound device config - ok
libxl: add PV sound device - ok

Reviewed-by: Oleksandr Grytsov <oleksandr_grytsov@epam.com>

**Comment by aanisov** [comment]
I take the stuff squash fixups and merge it. This is the last call for comments. You have few minutes to say a word.

**Comment by otyshchenko1** [comment]
Coproc/iommu conflicts were resolved properly.

**Pull request closed without merging**
