### PR TITLE
XEN 4.11 migration

### PR DESCRIPTION
**Pull request by aanisov**

### CODE REVIEW

**Comment by otyshchenko1** [comment]
https://github.com/xen-troops/xen/commit/be1f7ea9e535fb97688baa28dd9ef92a5d4fc52d is missed

**Comment by aanisov** [comment]
https://github.com/xen-troops/xen/pull/120/commits/a2385c946945a55cf3b1b13eecaf434875fced75 added

**Comment by otyshchenko1** [comment]
Most likely you need to update your PR. Some patches has been added to our master recently.

**Comment by aanisov** [comment]
outdated

**Pull request closed without merging**
