### PR TITLE
Fix vGPU-Img debug build

### PR DESCRIPTION
**Pull request by andr2000**
Signed-off-by: Oleksandr Andrushchenko <oleksandr_andrushchenko@epam.com>

### CODE REVIEW

**Comment by andr2000** [comment]
bump

**Comment by aanisov** [comment]
Please close this while @otyshchenko1 have its #104 merged.

**Comment by otyshchenko1** [comment]
Some mistake has happened, I didn't draw my attention that the similar pr was already present and did the same patch today.

**Comment by andr2000** [comment]
Duplicate has been merged

**Pull request closed without merging**
