### PR TITLE
Fixes regarding releasing resources

### PR DESCRIPTION
**Pull request by otyshchenko1**

### CODE REVIEW

**Comment by otyshchenko1** [comment]
Guys, excuse me, but, are you going to review?

**Comment by andr2000** [comment]
lgtm, rb

**Comment by otyshchenko1** [comment]
Not yet. But, I hope it will be upstreamed. I decided to push it to our vgpu-dev branch in order to keep it in place

**Comment by aanisov** [comment]
Are they at least published?

**Comment by otyshchenko1** [comment]
Yes

**Pull request merged**
