### PR TITLE
Draft: Introducing SCMI-Mediator for Rcar boards

### PR DESCRIPTION
**Pull request by oleksiimoisieiev**
SCMI-Mediator is responsible for redistribution SCMI requests between Domains and ATM-TF.
Xen manages device access and handles SCMI messages from the Domains.
This feature allows to control the devices, passedthrough to the different Domains.

TODO:
- add ac_assign_device_call to DomU init
- test rpi real device in DomU
- confirm work with rpi5

### CODE REVIEW

**Comment by klogg** [comment]
Is it possible to split it into "generic" and "rcar" + "rpi" parts?

**Comment by oleksiimoisieiev** [comment]
> Is it possible to split it into "generic" and "rcar" + "rpi" parts?

SCMI Mediator meant to be generic and build and work on both setups. 
I think first 3 commits that are not related to SCMI directly can be dropped from this PR as needed only for rpi5. So I can create 2 prs - for rcar/generic and for rpi5. But this will complicate testing process.
Is it what you ask?

**Comment by klogg** [comment]
> > Is it possible to split it into "generic" and "rcar" + "rpi" parts?
> 
> SCMI Mediator meant to be generic and build and work on both setups. I think first 3 commits that are not related to SCMI directly can be dropped from this PR as needed only for rpi5. So I can create 2 prs - for rcar/generic and for rpi5. But this will complicate testing process. Is it what you ask?

yes, but also - maybe it is worth to separate rcar-specific patches (if any), too

**Comment by oleksiimoisieiev** [comment]
> > > Is it possible to split it into "generic" and "rcar" + "rpi" parts?
> > 
> > 
> > SCMI Mediator meant to be generic and build and work on both setups. I think first 3 commits that are not related to SCMI directly can be dropped from this PR as needed only for rpi5. So I can create 2 prs - for rcar/generic and for rpi5. But this will complicate testing process. Is it what you ask?
> 
> yes, but also - maybe it is worth to separate rcar-specific patches (if any), too

Okay. I'll make 2 separate PRs after finishing testing process

**Comment by oleksiimoisieiev** [comment]
@lorc @GrygiriiS Updated pr. 
```
Changes V1 -> V2
- add assign DT device for DomUs.
- tested with usb reset on DomD
- add memory mapping for Domain-0 (it was working event without it... weird)
TODO:
- test with device in Domain-0
- test with rpi5
- split to rpi5 pull and rcar pull
POSTPONED:
- flask support for new domctl. will work with flask=permissive for now.
```

**Comment by oleksiimoisieiev** [comment]
Closing as obsolete.

**Pull request closed without merging**
