### PR TITLE
Add support for pv_camera

### PR DESCRIPTION
**Pull request by rshym**

### CODE REVIEW

**Comment by otyshchenko1** [comment]
a02d7a6f and faac370c are not needed.

**Comment by otyshchenko1** [comment]
These patches are in the product meta layer already.

**Comment by rshym** [comment]
Thanks for pointing. Patches a02d7a6 and faac370 are removed from pull request.

**Comment by andr2000** [comment]
I would mark patch "libxl: add vcamera device" as incomplete: it adds most of the functionality required to create a domain, but still some pieces are missing.

**Comment by rshym** [comment]
@aanisov could you please review?

**Comment by aanisov** [comment]
FWIW lgtm

**Comment by rshym** [comment]
@aanisov thanks for review. Could you please merge?

**Comment by aanisov** [comment]
done

**Pull request merged**
